### PR TITLE
php73 and symfony5 support

### PR DESCRIPTION
**Pull request by jspaetzel**
Small change set which minimally resolves php73 / symfony5 support.
See build: https://travis-ci.org/github/lightSAML/lightSAML/builds/722946552

There's some other branches where folks have done the same stuff, just with more changes then I wanted at once.
* https://github.com/4Labs/lightSAML
* https://github.com/lightSAML/lightSAML/pull/129/files / https://github.com/thephplab/lightsaml

### CODE REVIEW

**Comment by jspaetzel** [comment]
Maintaining a fork with these changes now under https://github.com/dropbox/lightSAML

**Comment by jspaetzel** [comment]
Got your invite @tmilos.

Will work up a PR from my fork back into lightSAML soon, probably sometime this weekend. I went a bit further with my fork then just the changes in this draft. Any preference on whether I do them as one large PR or piecewise?

**Comment by frostieDE** [comment]
I guess it depends on the changes you made. In my optinion, it should only contain code that is necessary so it works with PHP 7.3 and Symfony 5.x. WDYT?

**Comment by jspaetzel** [comment]
See here. The notes at the top go over the steps I took. 
https://github.com/dropbox/lightSAML/commit/43b8b09dcf3b980358fb2a3c7c5f357f7e7c073f

It's been a minute but I think the formatting changes all came from updating php-cs-fixer to php-cs-fixer-v2. I didn't do any of that manually. I'm happy to do that as a separate commit though if folks prefer to see that broken out. Might have to strip out more of the build stuff to make that work though.

**Comment by jspaetzel** [comment]
Doing a more proper minimal change-set here: https://github.com/lightSAML/lightSAML/pull/139

**Pull request closed without merging**
