### PR TITLE
Fixing parsing date

### PR DESCRIPTION
**Pull request by JEDIBC**
…with difference to Greenwich time (GMT) with colon between hours and minutes

see #111

### CODE REVIEW

**Comment by JEDIBC** [comment]
@tmilos ready to merge :+1:

**Comment by tmilos** [comment]
LightSAML now accepts following formats:
* 2014-10-04T05:07:30Z
* 2014-10-04T05:07:30+00:00
* 2014-10-04T05:07:30.000+00:00

**Comment by tmilos** [comment]
Released in v1.3.6
@JEDIBC Thanks for contribution

**Comment by JEDIBC** [comment]
@tmilos no thanks you for this library :+1:

**Pull request merged**
