### PR TITLE
Add support for SSO logout

### PR DESCRIPTION
**Pull request by axelvnk**
Please comment if changes need to be made, will process ASAP. I will also open up a pull request for the SpBundle.

### CODE REVIEW

**Comment by axelvnk** [comment]
Will add unit tests tomorrow and fix scrutinizer issue.

**Comment by Neirda24** [comment]
Any news on this ? Will it be merged ?

**Comment by axelvnk** [comment]
@Neirda24 probably not since they made a separate bundle for this . I talk about it here https://github.com/lightSAML/SpBundle/pull/64

**Comment by Cyrille37** [comment]
Hello
Perhaps closing this pull request ? it will avoid confusion for visitors :-)

Regards & Cheers

**Pull request closed without merging**
