### PR TITLE
Upgrade to PHP 7.2 & Symfony 5

### PR DESCRIPTION
**Pull request by william-suppo**

### CODE REVIEW

**Comment by celloman** [comment]
Are there any updates on this? Is anyone maintaining this repo anymore?

**Comment by william-suppo** [comment]
I try to maintain this project now here => https://github.com/thephplab/lightsaml

**Comment by tmilos** [comment]
@william-suppo would you like to be maintainer of this project?

**Comment by william-suppo** [comment]
Hello @tmilos, I'm in !

**Comment by jspaetzel** [comment]
Resolved by https://github.com/lightSAML/lightSAML/pull/139
I like some of the other changes in this PR but there are too many at once.

**Pull request closed without merging**
